version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
permissions:
  - object: /var/www/html
    owner: webuser
    group: webgroup
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: webuser
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: webuser
  ValidateService:
    - location: scripts/validate-service.sh
      timeout: 300